<?php

/**
* Main controller model
*/
class Main
{
    
    static public function test()
    {
        return array(
                    array("z"=>"Nulla semper tellus id nunc interdum feugiat. Sed nec metus"),
                    array("z"=>"Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero mauris,"),
                    array("z"=>"Mauris eu turpis. Nulla aliquet. Proin velit. Sed malesuada augue"),
                    array("z"=>"purus. Nullam scelerisque neque sed sem egestas blandit. Nam nulla"),
                    array("z"=>"vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum ut eros"),
                    array("z"=>"quis, tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla."),
                    array("z"=>"lorem, eget mollis lectus pede et risus. Quisque libero lacus,"),
                    array("z"=>"parturient montes, nascetur ridiculus mus. Donec dignissim magna a tortor."),
                    array("z"=>"ipsum ac mi eleifend egestas. Sed pharetra, felis eget varius"),
                    array("z"=>"Duis elementum, dui quis accumsan convallis, ante lectus convallis est,"),
                    array("z"=>"odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam"),
                    array("z"=>"vitae odio sagittis semper. Nam tempor diam dictum sapien. Aenean"),
                    array("z"=>"non, feugiat nec, diam. Duis mi enim, condimentum eget, volutpat"),
                    array("z"=>"sem semper erat, in consectetuer ipsum nunc id enim. Curabitur"),
                    array("z"=>"at pede. Cras vulputate velit eu sem. Pellentesque ut ipsum"),
                    array("z"=>"ultricies dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus."),
                    array("z"=>"dis parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque"),
                    array("z"=>"augue scelerisque mollis. Phasellus libero mauris, aliquam eu, accumsan sed,"),
                    array("z"=>"amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing"),
                    array("z"=>"Fusce aliquet magna a neque. Nullam ut nisi a odio"),
                    array("z"=>"lorem lorem, luctus ut, pellentesque eget, dictum placerat, augue. Sed"),
                    array("z"=>"sed libero. Proin sed turpis nec mauris blandit mattis. Cras"),
                    array("z"=>"amet ultricies sem magna nec quam. Curabitur vel lectus. Cum"),
                    array("z"=>"eget ipsum. Suspendisse sagittis. Nullam vitae diam. Proin dolor. Nulla"),
                    array("z"=>"semper, dui lectus rutrum urna, nec luctus felis purus ac"),
                    array("z"=>"Proin nisl sem, consequat nec, mollis vitae, posuere at, velit."),
                    array("z"=>"massa. Quisque porttitor eros nec tellus. Nunc lectus pede, ultrices"),
                    array("z"=>"dui augue eu tellus. Phasellus elit pede, malesuada vel, venenatis"),
                    array("z"=>"semper tellus id nunc interdum feugiat. Sed nec metus facilisis"),
                    array("z"=>"Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque"),
                    array("z"=>"aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus quam"),
                    array("z"=>"sem, vitae aliquam eros turpis non enim. Mauris quis turpis"),
                    array("z"=>"cursus et, magna. Praesent interdum ligula eu enim. Etiam imperdiet"),
                    array("z"=>"Nunc ut erat. Sed nunc est, mollis non, cursus non,"),
                    array("z"=>"nec urna suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum ante"),
                    array("z"=>"amet risus. Donec egestas. Aliquam nec enim. Nunc ut erat."),
                    array("z"=>"facilisis. Suspendisse commodo tincidunt nibh. Phasellus nulla. Integer vulputate, risus"),
                    array("z"=>"Vivamus nibh dolor, nonummy ac, feugiat non, lobortis quis, pede."),
                    array("z"=>"ac mi eleifend egestas. Sed pharetra, felis eget varius ultrices,"),
                    array("z"=>"lacus. Etiam bibendum fermentum metus. Aenean sed pede nec ante"),
                    array("z"=>"tellus. Aenean egestas hendrerit neque. In ornare sagittis felis. Donec"),
                    array("z"=>"habitant morbi tristique senectus et netus et malesuada fames ac"),
                    array("z"=>"Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie"),
                    array("z"=>"eu odio tristique pharetra. Quisque ac libero nec ligula consectetuer"),
                    array("z"=>"habitant morbi tristique senectus et netus et malesuada fames ac"),
                    array("z"=>"cubilia Curae; Donec tincidunt. Donec vitae erat vel pede blandit"),
                    array("z"=>"Etiam bibendum fermentum metus. Aenean sed pede nec ante blandit"),
                    array("z"=>"non enim. Mauris quis turpis vitae purus gravida sagittis. Duis"),
                    array("z"=>"mollis. Duis sit amet diam eu dolor egestas rhoncus. Proin"),
                    array("z"=>"dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur"),
                    array("z"=>"sit amet luctus vulputate, nisi sem semper erat, in consectetuer"),
                    array("z"=>"rutrum. Fusce dolor quam, elementum at, egestas a, scelerisque sed,"),
                    array("z"=>"ante dictum mi, ac mattis velit justo nec ante. Maecenas"),
                    array("z"=>"purus. Maecenas libero est, congue a, aliquet vel, vulputate eu,"),
                    array("z"=>"enim mi tempor lorem, eget mollis lectus pede et risus."),
                    array("z"=>"ante blandit viverra. Donec tempus, lorem fringilla ornare placerat, orci"),
                    array("z"=>"Morbi sit amet massa. Quisque porttitor eros nec tellus. Nunc"),
                    array("z"=>"risus. Donec egestas. Duis ac arcu. Nunc mauris. Morbi non"),
                    array("z"=>"tempus scelerisque, lorem ipsum sodales purus, in molestie tortor nibh"),
                    array("z"=>"euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate"),
                    array("z"=>"ac mattis semper, dui lectus rutrum urna, nec luctus felis"),
                    array("z"=>"Donec egestas. Aliquam nec enim. Nunc ut erat. Sed nunc"),
                    array("z"=>"neque et nunc. Quisque ornare tortor at risus. Nunc ac"),
                    array("z"=>"Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero mauris,"),
                    array("z"=>"sem ut cursus luctus, ipsum leo elementum sem, vitae aliquam"),
                    array("z"=>"pede et risus. Quisque libero lacus, varius et, euismod et,"),
                    array("z"=>"gravida nunc sed pede. Cum sociis natoque penatibus et magnis"),
                    array("z"=>"dui, in sodales elit erat vitae risus. Duis a mi"),
                    array("z"=>"interdum enim non nisi. Aenean eget metus. In nec orci."),
                    array("z"=>"aliquet. Proin velit. Sed malesuada augue ut lacus. Nulla tincidunt,"),
                    array("z"=>"dictum mi, ac mattis velit justo nec ante. Maecenas mi"),
                    array("z"=>"porttitor interdum. Sed auctor odio a purus. Duis elementum, dui"),
                    array("z"=>"Cras vulputate velit eu sem. Pellentesque ut ipsum ac mi"),
                    array("z"=>"tempus eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi."),
                    array("z"=>"montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique"),
                    array("z"=>"tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et, rutrum"),
                    array("z"=>"non ante bibendum ullamcorper. Duis cursus, diam at pretium aliquet,"),
                    array("z"=>"nibh. Donec est mauris, rhoncus id, mollis nec, cursus a,"),
                    array("z"=>"Donec at arcu. Vestibulum ante ipsum primis in faucibus orci"),
                    array("z"=>"varius ultrices, mauris ipsum porta elit, a feugiat tellus lorem"),
                    array("z"=>"Nullam ut nisi a odio semper cursus. Integer mollis. Integer"),
                    array("z"=>"sagittis semper. Nam tempor diam dictum sapien. Aenean massa. Integer"),
                    array("z"=>"per inceptos hymenaeos. Mauris ut quam vel sapien imperdiet ornare."),
                    array("z"=>"nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus."),
                    array("z"=>"tempor augue ac ipsum. Phasellus vitae mauris sit amet lorem"),
                    array("z"=>"nec luctus felis purus ac tellus. Suspendisse sed dolor. Fusce"),
                    array("z"=>"iaculis odio. Nam interdum enim non nisi. Aenean eget metus."),
                    array("z"=>"ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida"),
                    array("z"=>"elit sed consequat auctor, nunc nulla vulputate dui, nec tempus"),
                    array("z"=>"cursus luctus, ipsum leo elementum sem, vitae aliquam eros turpis"),
                    array("z"=>"eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est."),
                    array("z"=>"dis parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse"),
                    array("z"=>"metus vitae velit egestas lacinia. Sed congue, elit sed consequat"),
                    array("z"=>"magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum metus."),
                    array("z"=>"torquent per conubia nostra, per inceptos hymenaeos. Mauris ut quam"),
                    array("z"=>"Sed id risus quis diam luctus lobortis. Class aptent taciti"),
                    array("z"=>"Vestibulum ante ipsum primis in faucibus orci luctus et ultrices"),
                    array("z"=>"ut mi. Duis risus odio, auctor vitae, aliquet nec, imperdiet"),
                    array("z"=>"nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra."),
                    array("z"=>"adipiscing, enim mi tempor lorem, eget mollis lectus pede et")
                );
    }
}