home:
    path:     /
    defaults: { _controller: VRoomWebsiteBundle:Public:home }

profile:
    path:     /profile/{id}-{name}
    defaults: { _controller: VRoomWebsiteBundle:Public:profile }

offer:
    path:     /register/offer
    defaults: { _controller: VRoomWebsiteBundle:Public:offer }

offer_details:
    path:     /offer/details/{id}-{start}-{end}
    defaults: { _controller: VRoomWebsiteBundle:Public:offerDetails }

register:
    pattern:  /register
    defaults: { _controller: VRoomWebsiteBundle:Security:register }

login:
    path:     /
    defaults: { _controller: VRoomWebsiteBundle:Public:home }

login_check:
    pattern:  /login_check

logout:
    pattern:  /logout